### ISSUE TITLE
Global Emergency

### ISSUE THREAD

**Issue by vgpastor** [chava100f/Prot_Civil#9]
Hola @chava100f 

Estamos creando un grupo de desarrollo de aplicaciones y funcionalidades, totalmente OpenSource, para ponerles a disposición de cualquier protección civil que las pueda necesitar de una manera totalmente gratuita.

Buscamos cualquier perfil, necesitamos desde personas para diseño, redacción de documentación, pruebas de las aplicaciones, programación de las mismas, etc.

También nos gustaría dar cabida a proyectos que ya han sido desarrollados como este tuyo para integrarlos dentro del catálogo de aplicaciones disponibles, ¿Crees que podría tener sentido?

https://globalemergency.online/news/buscamos-voluntarios/

Una de las partes más importantes es la opinión de la comunidad por lo que también necesitamos las opiniones sobre las diferentes plataformas de cualquier persona del mundillo, para realmente desarrollar cosas que sean usables y a medida de todos.

Espero que podamos contactar pronto.

Un Saludo.

**Comment by chava100f** [comment]
Hola Victor que tal, 

Por supuesto!, una disculpa por no haber visto antes este mensaje, pero si me encantaría participar como voluntario en tu equipo. De hecho mi proyecto no es tan profesional y no tiene las herramientas mas actuales, pero si sirve para alguien con gusto se puede usar sin problemas. Incluso si es necesario que le de mantenimiento lo reviso para que funcione al 100%.

También ya envíe mi registro al equipo de GlobalEmergency, para ayudar en lo que pueda.

Muchas gracias por la invitación. :D
